name: Deploy Test

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: SSH connection test
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "SSH connection successful"
            hostname
            cd ~/MokuQest
            git branch --show-current